### ISSUE TITLE
Error loading Kiwiirc Cors issue

### ISSUE THREAD

**Issue by Shillos** [kiwiirc/kiwiirc#1109]
Got an issue with cors on my kiwi chat all of a sudden i get this (in browser debug as shown on screenshot): 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localdev.clients.kiwiirc.com/webirc/kiwiirc/info?t=1563189050299. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
I tried making as new again and rebuild it so i removed my old kiwi folder and git cloned it again same issue. Can't get it to load. When pressing start button on the welcome screen it does nothing. Tested also on Firefox and Chrome, nothing changed! Also other users couldn't get connected on the webchat. Here is a screenshot of the issue:
![2019-07-15_1419](https://user-images.githubusercontent.com/491386/61212793-ecc01180-a70b-11e9-8bac-06f0ae9419a7.png)

**Comment by Shillos** [comment]
This is strange. For 2 days I couldn't get connected and now all of a sudden it works fine.

**Comment by prawnsalad** [comment]
Hey, that `localdev.clients.kiwiirc.com` address is only to be used to local development. It will never have complete uptime since it doesn't get monitored as much as the production servers. (kiwiirc.com had some networking issues over the weekend and that server has just been fixed now).

Ideally you should be running your own kiwi / webircgateway server on your own servers, then it's not relying on kiwiirc.com. https://github.com/kiwiirc/webircgateway
