### ISSUE TITLE
Hide join/part in link

### ISSUE THREAD

**Issue by PowaBanga** [kiwiirc/kiwiirc#121]
hi all,

So this is a link:
`https://kiwiirc.com/client/IRCSERVER/?&theme=relaxed#Channel`

my question is : there is way to unselect notifycations for join/part automaticly in the link, like 
`https://kiwiirc.com/client/IRCSERVER/?&theme=relaxed&joinpart=0#Channel`

For that the users do not need to go in setting to change that...

**Comment by prawnsalad** [comment]
This isnt available in the URL as putting every possible setting in the URL would be a mess.

There will soon be a way to create custom clients with all these settings so that you get a unique URL for a client with all your settings pre-set. When this is ready it will be announced on twitter @kiwiirc
