### ISSUE TITLE
Favicon doesn't work.

### ISSUE THREAD

**Issue by c0ncord2** [kiwiirc/kiwiirc#1219]
Favicon relies on lax privacy settings.
Properly configured Firefox blocks canvas extraction, what makes Kiwiirc favicon appear as a white square.

![screenshot](https://user-images.githubusercontent.com/59669788/72487650-9d67b480-3806-11ea-9371-4743b42cedd7.png)

![screenshot](https://user-images.githubusercontent.com/59669788/72487764-f5062000-3806-11ea-87f6-a44f4ee0a25b.png)

**Comment by prawnsalad** [comment]
I'm assuming that you have `privacy.resistFingerprinting` enabled in Firefox? If so, that's what is causing this issue. Since the browser with this setting returns incorrect values by design there is nothing we can do here. It is expected that disabling features in your browser will break web app functionality.
