### ISSUE TITLE
Configure username, realname and send_quit_on_client_close when using direct websocket connection

### ISSUE THREAD

**Issue by finalhit** [kiwiirc/kiwiirc#1345]
When connecting directly to IRCd using websockets (without webircgateway), it would be nice to be able to configure the following in config.json:
- username (mentioned in the source code as network.username)
- realname (mentioned in the source code as network.gecos)
- send_quit_on_client_close

Those options are present in webircgateway [configuration file](https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example).

**Comment by Shillos** [comment]
it's not needed in config.json when you already have webircgateway plugin added in kiwiirc config.json then you just need to config the webircgateway.

**Comment by finalhit** [comment]
Don't want to use webircgateway any longer, IRCd has WebSockets support.

**Comment by prawnsalad** [comment]
I'm indifferent for setting the username but just so I understand its use, in what way would you want to be using it? I'm struggling to see the use for it in a web client as it can easily be changed by the user and isn't used by an ident lookup. The case I've heard over the years is so that networks can check if a user is a web user - in which case the username is better set either in webircgateway or the IRCd itself.

Realname can be set via `startupOptions.gecos`.

The `send_quit_on_client_close` option in webircgateway is for when a client closes the page without sending a `QUIT`, which doesn't make much sense when not using webircgateway.

**Comment by westor7** [comment]
I personally agree to have options in config in cases that someone uses websockets and not webircgateway, personally in my case that i host more than 3 different kiwiirc would be useful.

```
startupOptions.nick
startupOptions.channel
startupOptions.server
startupOptions.port
startupOptions.tls
startupOptions.gecos
startupOptions.username
startupOptions.quit
```

And if someone just enable the ```direct: true``` then it will use these if not then just use the webircgateway settings.

**Comment by finalhit** [comment]
```startupOptions.gecos``` doesn't work properly, it still shows https://kiwiirc.com/ as realname.

We use ```username``` to differentiate clients.

If we have ```send_quit_on_client_close``` in webircgateway, don't see a reason not to have it here.

**Comment by finalhit** [comment]
```startupOptions.gecos``` doesn't work properly, it always shows https://kiwiirc.com/ as a realname.

Does the patch refer to ```startupOptions.username```?

**Comment by westor7** [comment]
gecos is working, just do "Forget me" on top left icon. => https://i.imgur.com/T3zaQdP.png

quits can only be handle from IRCD side, because when you close the browser/tab the connection is closed and you cannot send anything to the server to handle that.

startupOptions.username is to change the ident.

The issue is closed if you need more question join on FreeNode #Kiwiirc .
