### ISSUE TITLE
Port to KaiOS

### ISSUE THREAD

**Issue by takov751** [kiwiirc/kiwiirc#1398]
**Is your feature request related to a problem? Please describe.**
Porting the kiwiirc to KaiOS https://developer.kaiostech.com/

**Describe the solution you'd like**
It seems kiwiirc would be a great candidate for a IRC client for the KaiOS,which is basically a OS based around webapps.
**Describe alternatives you've considered**

**Additional context**
My only concern is the small resolution of these phones and that might need additional configuration control the apps with specific function buttons and arrow keys.

Just writing this feature request to start conversation regarding this platform.

**Comment by prawnsalad** [comment]
Hi, yes the resolution issue you mentioned would be a major thing. Until someone tries running kiwi on it I'm would have to guess a lot of the UI would have to be refactored for that. It would also need a control refactor since it looks (correct me if I'm wrong?) like it's not a touch screen interface either?

It sounds like a fair amount of fiddly work to get it running on there if I'm honest.

**Comment by takov751** [comment]
I will close this issue thread, as I reconsidered this would be a real pain in the bacon for those whom maintain this and need a lot effort. Thank you for anyone time whom spend to think about supporting this platform.
