### ISSUE TITLE
share_typing not working

### ISSUE THREAD

**Issue by TimeRider07** [kiwiirc/kiwiirc#1519]
Hello, I am trying to enable this configuration option "share_typing" for kiwiirc but it's not working.

I am using inspircd-3.7.0
Modules loaded:
m_ircv3_ctctags.so
m_ircv3.so
m_cap.so

In my kiwiirc 
client.json, share_typing = true,

Link to my kiwiirc chat: https://app.chatsansar.com

I don't know what is not working but share_typing is not being enabled.

Please help!

**Comment by ItsOnlyBinary** [comment]
Seems the issue is the kiwiirc you have installed is too old.

You have 1.3.0 and share_typing was added in 1.4.0 and latest version is 1.5.1.

Either update your packaged install (webircgateway+kiwiirc), and/or update the client files (this source) in /usr/share/kiwiirc

If building this source i recommend copying the contents of dist/* to /usr/share/kiwiirc_master/ then updating /etc/kiwiirc/config.conf to point to the new directory so that it does not cause any conflicts with package updating in the future

**Comment by TimeRider07** [comment]
Yeah, It's the problem with version 1.3.0 I have. I got it working in the new version. Thank you.
