### ISSUE TITLE
users sidebar

### ISSUE THREAD

**Issue by otello89** [kiwiirc/kiwiirc#1539]
Hi,
present only in the mobile resolution. when you change from one channel to another, the users sidebar automatically appears.

[https://i.imgur.com/pxBTHLa.mp4](url)

**Comment by ItsOnlyBinary** [comment]
This is fixed in master so closing this issuse, if you need more help than below I will still see replies to this issue or you can drop into #kiwiirc on irc.freenode.net

If you installed the packaged version:
download & extract https://builds.kiwiirc.com/zips/kiwiirc_master.zip
copy the contents of `dist/*` to `/usr/share/kiwiirc_master`
symlink config to /etc `rm /usr/share/kiwiirc_master/static/config,json && ln -s /etc/kiwiirc/client.json /usr/share/kiwiirc_master/static/config,json`
edit `/etc/config.conf` `[fileserving]` `webroot` to `/usr/share/kiwiirc_master`
restart kiwiirc `systemctl restart kiwiirc`

**Comment by otello89** [comment]
Hi, i'm using https://kiwiirc.com/nextclient/irc.freenode.net

i can't install kiwi :(

**Comment by ItsOnlyBinary** [comment]
oh would appear kiwiirc.com requires an update @prawnsalad 

hopefully prawnsalad will see this soon and get some time test and action it.

**Comment by otello89** [comment]
Ok guys thank you so much i appreciate much :)

**Comment by otello89** [comment]
Hi, any news about this bug?

**Comment by otello89** [comment]
@prawnsalad  is possible to resolve this bug? :) Thanks so much

**Comment by prawnsalad** [comment]
@otello89 ill be getting to an update before end of this week :)
