### ISSUE TITLE
SSL cert for do-e.clients.kiwiirc.com has expired

### ISSUE THREAD

**Issue by AltitudeApps** [kiwiirc/kiwiirc#1660]
Perhaps it will get updated with a fresh certificate the next time the automated cert renewal happens, but it hasn't happened as of yet.

**Comment by sergip76** [comment]
Yes, this is the reason because KiwiIRC web widget doesn't work from yesterday.

When trying to connect to a channel this is the error:
We couldn't connect to the server :( Unknown error

This is the error in console:
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “do-e.clients.kiwiirc.com”, which could put your confidential information at risk. (info, line 0)
https://do-e.clients.kiwiirc.com/webirc/kiwiirc/info?sid=3a8n5f88wocgc&p=1&t=1646979407565

**Comment by roiconde** [comment]
@prawnsalad

Mentioning him just in case...

**Comment by AltitudeApps** [comment]
It's working now.  Thanks!

**Comment by sergip76** [comment]
Not for me. It doesn't work yet.

**Comment by AltitudeApps** [comment]
It has occurred again, it looks like the cert expired about a half hour ago.  

![image](https://user-images.githubusercontent.com/70041186/167516346-27f28963-0b82-473e-a2cb-f435b0ce5acd.png)

**Comment by AltitudeApps** [comment]
It's fixed !!

**Comment by slugan** [comment]
Hi, the certificate expired again two years ago:
```
        Issuer: C=US, O=Let's Encrypt, CN=R10
        Validity
            Not Before: Sep 23 22:18:35 2024 GMT
            Not After : Dec 22 22:18:34 2024 GMT
        Subject: CN=*.clients.kiwiirc.com
```
This blocks the web client demo from working, throwing a `SEC_ERROR_EXPIRED_CERTIFICATE` error when trying to connect with Firefox. Maybe a problem with the `certbot` configuration?
