### ISSUE TITLE
Custom client builder

### ISSUE THREAD

**Issue by Sh4d0wless** [kiwiirc/kiwiirc#1851]
hello
why "Custom client builder" does not work?
i did everything as needed on https://kiwiirc.com/clientbuilder/
but anyway widget iframe does not work... sorry for my bad english...

**Comment by XaibiAslam** [comment]
I think there is a problem with the code, because when we save the fields we get 500 error. Even I email them but no response.

**Comment by Depresst0** [comment]
> I think there is a problem with the code, because when we save the fields we get 500 error. Even I email them but no response.

This error is caused by a missed page edit, the client builder you (@XaibiAslam) are describing is the old (**COMPLETELY DISCONTINUED!!**) builder, indeed NOT found at @Sh4d0wless's link. They did not update the main page to have the nextclient builder, found at [https://kiwiirc.com/clientbuilder](https://kiwiirc.com/clientbuilder). I made this mistake myself, someone from the project should update the kiwiirc.com home page, as it also has old UI (Topbar and Buttons)

**Comment by ItsOnlyBinary** [comment]
Unfortunately this is support for kiwiirc the open-source project and not kiwiirc.com

I am unable to help with this issue
