### ISSUE TITLE
Is it possible to set the password on auto_connect?

### ISSUE THREAD

**Issue by anhofmann** [kiwiirc/kiwiirc#194]
I want to pass the nick and the password to kiwiirc on startup. It works like this: https://my.server/kiwi/?nick=something but I can't add "&password=foobar". Is there a way to achieve this? I maintain a browser based mmorpg and use a flash based IRC client where every user has their own IRC server password which they don't need to type in (and mostly don't know). The chat loads in a iframe and connects automatically. Is it possible to do this with kiwiirc?

**Comment by prawnsalad** [comment]
This is possible, but not via the URL. For a much more secure way so that you don't have user passwords appearing in logs and browser historys you can have your website serve a config file that includes the password and server for each user on the fly.

https://github.com/kiwiirc/kiwiirc/wiki/Configuration#loading-the-config-file

Load the config from yourwebsite.com/kiwiconfig.php which you fill in the connection info based on your user session. The `autoConnect` and `password` config options are described here https://github.com/kiwiirc/kiwiirc/wiki/Configuration#startupoptions

**Comment by anhofmann** [comment]
Nice! When I've read the documentation I didn't understood this, thank you for the explanation!
