### ISSUE TITLE
is it possible to execute commands after connecting to the irc network?

### ISSUE THREAD

**Issue by anhofmann** [kiwiirc/kiwiirc#197]
We want to register and identify every user automatically with nickserv. Most of our users have no clue what IRC is. So our old client executes "/msg nickserv register" and identify on every connect. Can we achieve this with kiwiirc?

**Comment by anhofmann** [comment]
Is it hard to implement? I'm willing to learn by myself how to do this, it would be great if I could get a hint where to look.

**Comment by prawnsalad** [comment]
This is possible using a plugin, though I'm not sure it's a great idea to auto register someone. How will they log back in to their account on another computer/browser?

If you create a plugin.js file somewhere hen include it into your index.html file *after* the kiwi .js files.

~~~
kiwi.plugin('your_plugin_name', function(kiwi) {
	kiwi.state.$on('irc:registered', function(event, network) {
		// network.ircClient.raw('raw irc commands here');
		// network.ircClient.say('nickserv', 'message for nickserv');
	});
});
~~~

**Comment by PandaloveFR** [comment]
Hi ! :) 

Was wondering if someone could help me out : 
How do we tell kiwiirc to execute a command on an IRC server when a user connects to that server ?
I've C/Ced the code from @prawnsalad and nothing happens. actual code here >> 
  |<script>
  |--
  | kiwi.plugin('webapp', function(kiwi) {
  | kiwi.state.$on('irc:registered', function(event, network) {
  | network.ircClient.raw('complaint something somethingelse anotherthing');
  | network.ircClient.say('x', 'message for x');
  | });
  | });
  | </script>
<< 

it seems like kiwiirc v2 is the problem but since i'm not sure; here's me posting here.

**Comment by prawnsalad** [comment]
Oops, the event name should have been `irc.registered`, not `irc:registered`

**Comment by PandaloveFR** [comment]
perfect =) Thanks @prawnsalad

**Comment by borigoto** [comment]
@PandaloveFR , this script worked for you?

This part: 

network.ircClient.raw('complaint something somethingelse anotherthing');

I try and not happened

**Comment by PandaloveFR** [comment]
yup worked for us @borigoto =) but with the correction irc.registered instead of irc:registered
