### ISSUE TITLE
libreJS support

### ISSUE THREAD

**Issue by bill-auger** [kiwiirc/kiwiirc#294]
we have noticed that this program does not work well with the current version of libreJS - would you be interested in patches to support libreJS users?

https://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by bill-auger** [comment]
ping @David_Hedlund

**Comment by bill-auger** [comment]
ping @davidhedlund

**Comment by davidhedlund** [comment]
@bill-auger Thank you.

**Comment by prawnsalad** [comment]
We have had this conversation many times and the end result is always the same. I'm happy to apply patches to kiwiirc if they don't effect the user experience. Somebody mentioned that they will be doing this and it never happened. Somebody else gave a .zip of the source saying "the changes are in here" (it wasn't a git repo) so that didn't help.

I'm closing this issue since we are repeating 2 year history yet again. If you would like to send some patches then please open a PR and we can take it from there.

**Comment by bill-auger** [comment]
excellent thank you

**Comment by davidhedlund** [comment]
@prawnsalad 

> I'm closing this issue since we are repeating 2 year history yet again. If you would like to send some patches then please open a PR and we can take it from there.

Can you please link this issue to it?

**Comment by bill-auger** [comment]
rather than that, i would leave this issue open, adding a relevant tags such as '[feature-request]', '[wish]', '[needs help]' so that it can be found in the future

i searched the issues here for the term 'libre' before opening this issue and got no results - so if there were discussions in the past, they are not apparent

**Comment by prawnsalad** [comment]
@davidhedlund @bill-auger The previous conversations were all on IRC unfortunately otherwise I would link them.

I have no intentions on working with librejs personally, purely down to the annoyance and frustration we've had over the past two years on this topic. For that reason, I'm not leaving an issue open for it. Feel free to open a PR with the needed changes and if it doesn't impact user experience then I'll be happy to merge it in. Apologies that you're the ones dealing with the result of previous librejs members input on kiwiirc, but that's all I have to say on this matter again.

**Comment by davidhedlund** [comment]
https://github.com/thelounge/thelounge/issues/2318

**Comment by davidhedlund** [comment]
https://github.com/qwebirc/qwebirc/issues/345

**Comment by prawnsalad** [comment]
@davidhedlund please stop mentioning this topic. As previously stated, I will accept a PR or usable patch from the master branch.

The librejs team that has interacted with kiwiirc over the years has tarnished your projects named due to the harassment and unwillingness to corporate. Your issues at https://github.com/thelounge/thelounge/issues/2318 and https://github.com/qwebirc/qwebirc/issues/345 have both brought up the same issues regarding the size and number of licenses and I don't see any decent response to this either.

Again, I am not willing to discuss this any further. Nor here or on IRC. If you want to suggest changes, make the changes and make a PR.

**Comment by davidhedlund** [comment]
> @davidhedlund please stop mentioning this topic. As previously stated, I will accept a PR or usable patch from the master branch.

My only intention was to link the issues, I didn't mean to push you to do anything.

> The librejs team that has interacted with kiwiirc over the years has tarnished your projects named due to the harassment and unwillingness to corporate.

What?

**Comment by davidhedlund** [comment]
Why did you say **your projects**? Do you accuse me for harassement?

**Comment by davidhedlund** [comment]
> The librejs team that has interacted with kiwiirc over the years has tarnished your projects named due to the harassment and unwillingness to corporate.

My projects? Did you mean "our projects" and not "your projects"?

**Comment by davidhedlund** [comment]
Also, I've never been part of the LibreJS team. I'm an admin of the [Free Software Directory](https://directory.fsf.org/wiki?title=Special:ListUsers&offset=&limit=1&username=David_Hedlund&group=sysop). The reason why @bill-auger pinged me was because we worked on various issues related to [free software evaluation](https://directory.fsf.org/wiki/Free_Software_Directory:Free_software_evaluation) including the [LibreJS IRC issues](https://directory.fsf.org/wiki?title=Free_Software_Directory:Free_software_evaluation&diff=63960&oldid=57376) that I brought up.

**Comment by davidhedlund** [comment]
> @davidhedlund please stop mentioning this topic. As previously stated, I will accept a PR or usable patch from the master branch.

My only intention was to link the issues, I didn't mean to push you to do anything.

> The librejs team that has interacted with kiwiirc over the years has tarnished your projects named due to the harassment and unwillingness to corporate.

My projects? Did you mean "our projects" and not "your projects"?

Also, I've never been part of the LibreJS team. I'm an admin of the [Free Software Directory](https://directory.fsf.org/wiki?title=Special:ListUsers&offset=&limit=1&username=David_Hedlund&group=sysop). The reason why @bill-auger pinged me was because we worked on various issues related to [free software evaluation](https://directory.fsf.org/wiki/Free_Software_Directory:Free_software_evaluation) including the [LibreJS IRC issues](https://directory.fsf.org/wiki?title=Free_Software_Directory:Free_software_evaluation&diff=63960&oldid=57376) that I brought up. Please do not blame the LibreJS team for that.

**Comment by bill-auger** [comment]
i can say without doubt that the librejs developers are not the
ones who evangelize it - david works on the FSF free software
directory, a distinct team from GNU librejs - i can not speak for
him; but im sure that he did not intend to pester

this particular issue is a rare occasion when someone
representing GNU or the FSF has requested someone to seek
cooperation from an outside project; and i am probably the only
such person that has ever contacted the kiwi-irc team for any
reason in the past - i assume that david was merely following-up
on the issue for clerical reasons, though perhaps too intrusively

i was asked simply to find out if librejs patches would be
accepted, because the FSF was interested in using this tool; and
i was fully satisfied with the original timely response - i also
agree that the cross-linking above was unnecessary and
inappropriate

it is almost always random users who take it upon themselves to
pester project maintainers publicly about licensing issues - i
often see vague or accusative licensing issues on other projects
posted by zealous users, with the result of annoying the devs -
and it is true that those people often do not offer to help
implement their feature requests in any way, as the most zealous
users are generally not programmers, from my experience - this
is unfortunate; but can not be avoided on a public access bug
tracker

**Comment by davidhedlund** [comment]
> i also agree that the cross-linking above was unnecessary and inappropriate.

@prawnsalad I apologize for the cross-linking and I will avoid this in the future. I learned a valuable lesson, thank you.
