### ISSUE TITLE
Notify about MemoServ memos

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwiirc#310]
Currently you have to go to the server tab to notice any memos. KiwiIRC UI could perhaps make some noise about memos.

Some ideas from kiwiirc channel discussion:

Elephantman: "needs a kind of inbox thing or faking the query window with an offline user, it's a great feature. Before that, the memoserv notice should be in active window though"

Beerbarian: take advantage of this existing functionality: https://github.com/kiwiirc/kiwiirc/blob/master/src/libs/IrcClient.js#L297

So the MemoServ notice would be pushed into the currently active channel.

**Comment by KoraggKnightWolf** [comment]
Instead of focusing just on MemoServ memos this issue should perhaps deal with notices altogether being more noticeable, as e.g. Global notices by network staff are also relevant. This seems to be an issue that is ongoing for a while and effecting people negatively in many ways. Perhaps having the status window show a notification bubble with the number of missed messages like in channels/queries would be the solution? 
This goes well with this issue arleady raised once before: https://github.com/kiwiirc/kiwiirc/issues/150
Hopefully KiwiIRC can receive a better displayal of notices because from what I personally see that is the only real flaw it has. Great to see you guys keep trying to improve it!

Regards,

Koragg

**Comment by mestaritonttu** [comment]
This is fixed by https://github.com/kiwiirc/kiwiirc/commit/49bbbc128a3bea4ae831972b7520de3594f1775b and related commits. Thanks!
