### ISSUE TITLE
Prevent (auto-)capitalisation

### ISSUE THREAD

**Issue by TonnesM** [kiwiirc/kiwiirc#347]
For instance, the "{{count}} people here" string appears to use auto-~~hyphenation~~capitalisation, so it’s displayed as e.g. "4 People Here". The same applies to localizations, and probably other strings.

Please prevent _any_ case of auto-capitalisation. This may be a bit more common and not that bad for English, but it’s a pain for localizers.

**Comment by prawnsalad** [comment]
Are you referring to auto capitalisation? ie. "Hello World" instead of "Hello world"

**Comment by TonnesM** [comment]
Correct, I tend to mix up these terms occasionally, sorry.

**Comment by prawnsalad** [comment]
Note for self: need to capture anywhere with `text-transform: capitalize;` and check if it's really needed

**Comment by AllanOcelot** [comment]
@prawnsalad  - I don't think there should be a case anywhere on the app where Capitalize should be applied - Uppercase should be (for some buttons / actions ) but I cannot think of a case where we should force text to Capitalize, especially since we deal with alot of translations, maybe I should do a search for it and remove all cases, and check for negative impact?.

**Comment by prawnsalad** [comment]
Yup, @AllanOcelot. https://github.com/kiwiirc/kiwiirc/search?q=capitalize&unscoped_q=capitalize

**Comment by AllanOcelot** [comment]
Issue fixed
