### ISSUE TITLE
Theme in Next Client Link/Embed?

### ISSUE THREAD

**Issue by digiwombat** [kiwiirc/kiwiirc#350]
Is there a way to default set the theme via the embed/link in the Next Client the way it works in the original?

**Comment by prawnsalad** [comment]
You can add `?theme=dark` to the URL for this.

**Comment by leo-lb** [comment]
@prawnsalad hey! is there a way also to set a custom theme with this? like `?theme=custom&theme-url=https://somedomain.org/theme.css`? thanks!

**Comment by prawnsalad** [comment]
@leo-lb No, external these are not supported yet as it can be easily abused. We do plan on supporting uploading themes soon though.

**Comment by leo-lb** [comment]
@prawnsalad thanks for the answer, I self hosted instead. If I can suggest some improvements in that area, it would have made it easier for me if there was a debian repo with arm64 packages (I am using a Raspberry Pi), so that I can self-host kiwiirc and also keep up with updates. A systemd service would be welcome also, right now running as a user using crontab. thanks again.

**Comment by prawnsalad** [comment]
Could you let me know if this installation package works? https://kiwiirc.com/downloads/kiwiirc_20.05.24.1-1_armel.deb

**Comment by leo-lb** [comment]
@prawnsalad I have a Model 3B+ and it's arm64 so if based on the name that package is for armel it will not work without additional steps (many additional armel userland packages, and maybe even qemu-user).
