### ISSUE TITLE
Message buttons in small screen padding

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#982]
The buttons on small screen messages could do with some padding

![image](https://user-images.githubusercontent.com/558946/57858072-e2eb6200-77df-11e9-8e3b-25016569fe13.png)

**Comment by AllanOcelot** [comment]
hmhmhm I'm 100% certain we have an existing PR that adds padding to this, shall look tomorrow.

**Comment by AllanOcelot** [comment]
@ItsOnlyBinary  it looks like since this issue was opened, padding for the buttons has been merged in 👍  ( Tested in all three layouts, traditional/modern and inline )

Please let me know if this is not the case and I'm missing something

![image](https://user-images.githubusercontent.com/11334905/58035632-1c460980-7b21-11e9-96d8-b00ee855f74c.png)

**Comment by ItsOnlyBinary** [comment]
All good allan thanks \o/
